apiVersion: v1
kind: Pod
metadata:
  labels:
    run: login-app
  name: login-app
spec:
  containers:
  - image: registry.gitlab.com/devops9104120/k8s-data/sample:v1
    name: login-app  
  restartPolicy: Always
  imagePullSecrets:
    - name: app-secret
